service: prompt-optimization-service
org: sitewiz
app: api

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - "arn:aws:dynamodb:${self:provider.region}:*:table/prompts"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/prompts/*"
        - Effect: Allow
          Action:
            - s3:*
            - s3-object-lambda:*
          Resource: "*"
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource:
            - "*"
        - Effect: Allow
          Action:
            - "states:StartExecution"
            - "states:DescribeExecution"
            - "states:GetExecutionHistory"
            - "states:StopExecution"
          Resource:
            - "arn:aws:states:${self:provider.region}:*:stateMachine:*"
            - "arn:aws:states:${self:provider.region}:${aws:accountId}:execution:*"
        - Effect: Allow
          Action:
            - "ecs:RunTask"
            - "ecs:DescribeTasks"
            - "ecs:StopTask"
          Resource:
            - "arn:aws:ecs:${self:provider.region}:${aws:accountId}:task-definition/*"
            - "arn:aws:ecs:${self:provider.region}:${aws:accountId}:cluster/*"
        - Effect: Allow
          Action:
            - "iam:PassRole"
          Resource:
            - "arn:aws:iam::${aws:accountId}:role/ecsTaskExecutionRole"

functions:
  promptOptimization:
    handler: lambda_function.handler
    runtime: python3.12
    package:
      patterns:
        - "utils.py"
        - "lambda_function.py"
    timeout: 900
    memorySize: 1280
    layers:
      - arn:aws:lambda:us-east-1:679946893962:layer:litellm:8
      - arn:aws:lambda:us-east-1:679946893962:layer:requests:1

package:
  individually: true
  patterns:
    - "!**" # Exclude everything by default
